# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('parametrizacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('privado', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, default='inmueble/default.jpg', null=True, upload_to='inmueble')),
                ('longitud', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_inmueble_administrador', to='usuarios.Usuario')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_inmueble_barrio', to='parametrizacion.DBarrio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_inmueble_tipo', to='parametrizacion.ETipo')),
            ],
            options={
                'db_table': 'inmueble_Inmueble',
                'verbose_name': 'Inmueble',
                'permissions': (('can_see_inmueble', 'can see inmueble'),),
            },
        ),
        migrations.CreateModel(
            name='BCuentaInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('noCuenta', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_cuentaInmueble_banco', to='parametrizacion.FBanco')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_cuentaInmueble_inmueble', to='inmueble.AInmueble')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_cuentaInmueble_municipio', to='parametrizacion.CMunicipio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_cuentaInmueble_tipo', to='parametrizacion.ETipo')),
            ],
            options={
                'db_table': 'inmueble_cuentaInmueble',
                'verbose_name': 'cuentaInmueble',
                'permissions': (('can_see_cuentaInmueble', 'can see cuentaInmueble'),),
            },
        ),
        migrations.CreateModel(
            name='CNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, default='noticia/default.jpg', null=True, upload_to='noticia')),
                ('activa', models.BooleanField(default=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_noticia_inmueble', to='inmueble.AInmueble')),
            ],
            options={
                'db_table': 'inmueble_noticia',
                'verbose_name': 'noticia',
                'permissions': (('can_see_notifica', 'can see notifica'),),
            },
        ),
        migrations.CreateModel(
            name='DDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('documento', models.FileField(upload_to='documentos')),
                ('activo', models.BooleanField(default=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_documento_inmueble', to='inmueble.AInmueble')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_documento_tipo', to='parametrizacion.ETipo')),
            ],
            options={
                'db_table': 'inmueble_documento',
                'verbose_name': 'documento',
                'permissions': (('can_see_documento', 'can see documento'),),
            },
        ),
        migrations.CreateModel(
            name='EIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'inmueble_indicador',
                'verbose_name': 'indicador',
                'permissions': (('can_see_indicador', 'can see indicador'),),
            },
        ),
        migrations.CreateModel(
            name='FVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreIndicador', models.CharField(max_length=50)),
                ('nombreIndicador2', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_vivienda_indicador1', to='inmueble.EIndicador')),
                ('indicador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_vivienda_indicador2', to='inmueble.EIndicador')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_vivienda_inmueble', to='inmueble.AInmueble')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_vivienda_tipo', to='parametrizacion.ETipo')),
            ],
            options={
                'db_table': 'inmueble_vivienda',
                'verbose_name': 'vivienda',
                'permissions': (('can_see_vivienda', 'can see vivienda'),),
            },
        ),
        migrations.CreateModel(
            name='GResidente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_residente_persona', to='persona.Persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_residente_tipo', to='parametrizacion.ETipo')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_residente_vivienda', to='inmueble.FVivienda')),
            ],
            options={
                'db_table': 'inmueble_residente',
                'verbose_name': 'residente',
                'permissions': (('can_see_residente', 'can see residente'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='eindicador',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='gresidente',
            unique_together=set([('vivienda', 'persona', 'activo')]),
        ),
        migrations.AlterUniqueTogether(
            name='fvivienda',
            unique_together=set([('nombreIndicador', 'nombreIndicador2')]),
        ),
        migrations.AlterUniqueTogether(
            name='ddocumento',
            unique_together=set([('titulo',)]),
        ),
        migrations.AlterUniqueTogether(
            name='cnoticia',
            unique_together=set([('inmueble', 'titulo')]),
        ),
        migrations.AlterUniqueTogether(
            name='bcuentainmueble',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='ainmueble',
            unique_together=set([('nombre',)]),
        ),
    ]
