# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='usuario/default.jpg', null=True, upload_to='usuario')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_usuario_persona', to='persona.Persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_usuario_tipo', to='parametrizacion.ETipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'db_table': 'usuario',
                'permissions': (('can_see_usuario', 'can see usuario'),),
            },
        ),
    ]
