# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField()),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'persona',
                'db_table': 'persona',
                'permissions': (('can_see_persona', 'can see persona'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set([('cedula',), ('correo',)]),
        ),
    ]
