# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='APais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('validaNit', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('can_see_pais', 'can see pais'),),
                'verbose_name': 'Pais',
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='BDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_departamento_pais', to='parametrizacion.APais')),
            ],
            options={
                'permissions': (('can_see_departamento', 'can see departamento'),),
                'verbose_name': 'Departamento',
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='CMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_municipio_departamento', to='parametrizacion.BDepartamento')),
            ],
            options={
                'permissions': (('can_see_municipio', 'can see municipio'),),
                'verbose_name': 'Municipio',
                'db_table': 'Municipio',
            },
        ),
        migrations.CreateModel(
            name='DBarrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_barrio_municipio', to='parametrizacion.CMunicipio')),
            ],
            options={
                'permissions': (('can_see_barrio', 'can see barrio'),),
                'verbose_name': 'Barrio',
                'db_table': 'Barrio',
            },
        ),
        migrations.CreateModel(
            name='ETipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.IntegerField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_tipo_modelo', to='contenttypes.ContentType')),
            ],
            options={
                'permissions': (('can_see_tipo', 'can see tipo'),),
                'verbose_name': 'Tipo',
                'db_table': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='FBanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('can_see_banco', 'can see banco'),),
                'verbose_name': 'Banco',
                'db_table': 'Banco',
            },
        ),
        migrations.AlterUniqueTogether(
            name='fbanco',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='apais',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='etipo',
            unique_together=set([('nombre',)]),
        ),
        migrations.AlterUniqueTogether(
            name='dbarrio',
            unique_together=set([('nombre', 'municipio')]),
        ),
        migrations.AlterUniqueTogether(
            name='cmunicipio',
            unique_together=set([('nombre', 'departamento')]),
        ),
        migrations.AlterUniqueTogether(
            name='bdepartamento',
            unique_together=set([('nombre', 'pais')]),
        ),
    ]
